name: Translation Helper

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: issue
        if: github.event_name == 'issues'
        uses: actions-cool/translation-helper@v1.1.1
        with: 
          translate-body: false

      - name: pr
        if: github.event_name == 'pull_request_target'
        uses: actions-cool/translation-helper@v1.1.1
        with: 
          translate-body: false
